chpasswd/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('chpasswd.views',

    url(r'^$', 'chpasswd_prompt', name='chpasswd_prompt'),
    url(r'^change$', 'chpasswd_change', name='chpasswd_change'),

)

django_project/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

# enable admin interface
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_project.views.home', name='home'),
    # url(r'^django_project/', include('django_project.foo.urls')),

    url(r'^$', RedirectView.as_view(url='/chpasswd/')),
    url(r'^chpasswd/', 
        include('chpasswd.urls', namespace="chpasswd")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

chpasswd/models.py
from django.db import models


class ADUser(models.Model):
    username = models.CharField(max_length=100)

    def __unicode__(self):
        return "ADUser: %s" % self.username


class PasswordChangeLog(models.Model):
    ad_user = models.ForeignKey('ADUser')
    source_ip = models.CharField(max_length=25)
    when = models.DateTimeField()
    success = models.BooleanField()
    fail_reason = models.TextField()

    def __unicode__(self):
        return "PasswordChangeLog: %s %s %s %s" % (
            self.ad_user, self.source_ip, self.when, self.success)

chpasswd/forms.py
from django import forms


class ChpasswdForm(forms.Form):
    user = forms.CharField()
    old_pass = forms.CharField()
    new_pass1 = forms.CharField()
    new_pass2 = forms.CharField()

chpasswd/views.py
#!/usr/bin/python

import datetime

from django.shortcuts import (
    render_to_response,
)
from django.template import RequestContext
from django.http import (
    HttpResponseBadRequest,
)
from django.utils.translation import ugettext as _

from chpasswd import chpasswd_ad
from forms import ChpasswdForm

from models import (
    ADUser,
    PasswordChangeLog,
)

from django.conf import settings


def chpasswd_prompt(request):
    return render_without_msg(request)


def render_without_msg(request):
    return render_with_msg(request)


def render_with_msg(request, msg=None, success=None):
    return render_to_response("chpasswd/chpasswd_prompt.html",
                              dictionary={"msg": msg, "success": success},
                              context_instance=RequestContext(request))


def chpasswd_change(request):
    if request.method == "POST":
        form = ChpasswdForm(request.POST)
        if form.is_valid():
            # sanity checks
            new_pass1 = form.cleaned_data["new_pass1"]
            new_pass2 = form.cleaned_data["new_pass2"]
            if new_pass1 != new_pass2:
                return render_with_msg(request,
                                        msg=_("Passwords do not match"),
                                        success=False)

            if len(new_pass1) < settings.CHPASSWD_MIN_PASSWORD_SIZE:
                return render_with_msg(request,
                                        msg=_("Password too short"),
                                        success=False)

            # auto add domain if not given
            (user, sep, domain) = form.cleaned_data["user"].partition("@")
            if not domain:
                user = "%s@%s" % (user, settings.CHPASSWD_DOMAIN)

            now = datetime.datetime.now()
            start = now - datetime.timedelta(
                seconds=settings.CHPASSWD_RATE_LIMIT_TIME)
            attempts = PasswordChangeLog.objects.filter(
                ad_user__username=user,
                when__range=[start, now],
                success=False)
            if len(attempts) >= settings.CHPASSWD_RATE_LIMIT_ATTEMPTS:
                return render_with_msg(request,
                            msg=_("Too many wrong attempts, try again later"),
                            success=False)

            (ad_user, created) = ADUser.objects.get_or_create(username=user)
            log = PasswordChangeLog.objects.create(
                ad_user=ad_user,
                source_ip=request.META["REMOTE_ADDR"],
                when=now)
            log.save()

            # now do the actual change
            try:
                chpasswd_ad(settings.CHPASSWD_DOMAIN,
                            user,
                            form.cleaned_data["old_pass"],
                            form.cleaned_data["new_pass1"])
            except Exception as e:
                log.success = False
                log.fail_reason = "%s: %s" % (type(e), str(e))
                log.save()
                return render_with_msg(request,
                                        msg=_("Failed to change password"),
                                        success=False)
            log.success = True
            log.save()

            return render_with_msg(request,
                                    msg=_("Password changed"),
                                    success=True)
    return HttpResponseBadRequest("Need POST")

chpasswd/templates/base.html
{% load url from future %}
{% load i18n %}


<!doctype html>
<html>
	<head>
		<title>{% trans "AD Password changer" %}</title>
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}components/bootstrap.css/index.css">
		<style type="text/css">
			.progress {
				/*margin-bottom: 0px;*/
				vertical-align: middle;
				display: inline-block;
				margin: 0px 7px 0px 7px;
				border: 1px;
			}
			.password-verdict {
				margin-left: 4px;
			}
		</style>
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="span3"></div>
				<div class="span6">
					<h1>{% trans "AD Password changer" %}</h1>
					{% block body %}{% endblock %}
				</div>
				<div class="span3"></div>
			</div>
		</div>
		<script type="text/javascript" src="{{ STATIC_URL }}components/jquery/jquery.min.js"></script>
		{% block js %}{% endblock %}
	</body>
</html>

chpasswd/templates/chpasswd/chpasswd_prompt.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}
{% block body %}

<form action="{% url 'chpasswd:chpasswd_change' %}" 
      method="post" 
      class="form-horizontal">
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Change Password" %}</legend>

    {% if msg != None %}
      <div class="alert alert-{{ success|yesno:"success,error,info" }}">
        {{ msg }}
      </div>
    {% endif %}

    <div class="control-group">
      <label class="control-label" for="user">{% trans "Username" %}</label>
      <div class="controls">
        <input id="user" name="user" type="text" placeholder="Username" class="input-large" required="">
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="old_pass">{% trans "Current Password" %}</label>
      <div class="controls">
        <input id="old_pass" name="old_pass" type="password" 
               placeholder="{% trans "Current Password" %}"
               class="input-large" required="">
        <span class="help-inline"></span>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="new_pass1">{% trans "New Password" %}</label>
      <div class="controls">
        <input id="new_pass1" name="new_pass1" type="password" 
               placeholder="{% trans "New Password" %}"
               class="input-large" required="" minlength="8"
               data-validation-callback-callback="pw_must_not_contain_username">
      </div>
    </div>

    <div class="control-group">
      <div class="controls" id="pwstrength">
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="new_pass2">{% trans "New Password (repeat)" %}</label>
      <div class="controls">
        <input id="new_pass2" name="new_pass2" type="password" 
               placeholder="{% trans "New Password (repeat)" %}"
               class="input-large" required=""
               data-validation-matches-match="new_pass1" 
               data-validation-matches-message="{% trans "Must match password entered above" %}" >
      </div>
    </div>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary pull-right">{% trans "Change Password" %}</button>
    </div>
  </fieldset>
</form>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ STATIC_URL }}components/zxcvbn/zxcvbn-async.js">
</script>
<script type="text/javascript" src="{{ STATIC_URL }}components/jqBootstrapValidation-1.3.7.min.js/index.js"></script>
<script type="text/javascript">
  function pw_must_not_contain_username($el, value, callback) {
    username = $('#user').val();
    callback({
      value: value,
      valid: !(value.indexOf(username) !== -1) || username == '',
      message: "{% trans "Password must not contain username!" %}"
    });
  }
  // FIXME: add function crack_time_display() that does the crack time
  //        calculation with i18n
  $(document).ready(function () {
      $('#new_pass1').keyup(function() {
        result = zxcvbn($('#new_pass1').val())
        //console.log("Entropy: "+result.entropy)
        //console.log("Crack time: "+result.crack_time_display)
        switch(result.score) {
            case 0: 
              $('#pwstrength').text("{% trans 'Password is very Weak' %}");
              break;
            case 1: 
              $('#pwstrength').text("{% trans 'Password is weak' %}");
              break;
            case 2: 
              $('#pwstrength').text("{% trans 'Password is medium' %}");
              break;
            case 3: 
              $('#pwstrength').text("{% trans 'Password is strong' %}");
              break;
            case 4: 
              $('#pwstrength').text("{% trans 'Password is very strong' %}");
              break;
        }
      });

      $('input,select,textarea').not('[type=submit]').jqBootstrapValidation();
  });
</script>
{% endblock %}